/* Generated by AN DISI Unibo */ 
package it.unibo.mockalarmdevice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Mockalarmdevice ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outred("$name | sub a broker")
						connectToMqttBroker( "tcp://localhost:1883" )
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t08",targetState="handleSonarData",cond=whenDispatch("mocksonardata"))
				}	 
				state("handleSonarData") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("mocksonardata(DIST)"), Term.createTerm("mocksonardata(DIST)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val DISTANCE = payloadArg(0)  
								CommUtils.outred("$name | pubblico $DISTANCE")
								//val m = MsgUtil.buildEvent(name, "mocksonarevent", "$DISTANCE" ) 
								publish(MsgUtil.buildEvent(name,"mocksonarevent","$DISTANCE").toString(), "sonardata" )   
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
			}
		}
} 
