/* Generated by AN DISI Unibo */ 
package it.unibo.coldstorageservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
class Coldstorageservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		 var currentStorage = 0
				val maxStorage=100
				var ready = true
				return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblack("--- coldStorageService active")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleStorageRequest",cond=whenRequest("storerequest"))
					transition(edgeName="t01",targetState="handleDiscargeFood",cond=whenRequest("dischargefood"))
				}	 
				state("handleStorageRequest") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("storerequest(FW)"), Term.createTerm("storerequest(FW)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outblack("--- storeRequest arrived")
								
								    		val requestStorage = payloadArg(0).toInt()
								    		val leftStorage = maxStorage -(currentStorage + requestStorage)
								    		if (leftStorage > 0){
								    			val TICKETNUMBER = "A12345"
								    			currentStorage +=  requestStorage
								CommUtils.outblack("--- ticket accepted $TICKETNUMBER")
								answer("storerequest", "ticketAccepted", "ticketAccepted($TICKETNUMBER)"   )  
								}else {
								CommUtils.outblack("--- ticket denied ")
								answer("storerequest", "replyTicketDenied", "ticketDenied(denied)"   )  
								} 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
				state("handleDiscargeFood") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("dischargefood(TICKETNUM)"), Term.createTerm("dischargefood(TICKETNUMBER)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outblack("--- dischargefood arrived")
								 
								    		val ticketNumber = payloadArg(0)
								    		if (ticketNumber != "EXPIRED"){
								CommUtils.outblack("--- charge taken $ticketNumber")
								answer("dischargefood", "replyChargeTaken", "replyChargeTaken(ARG)"   )  
								}else {
								CommUtils.outblack("--- ticket expired $ticketNumber")
								answer("dischargefood", "replyTicketExpired", "replyTicketExpired(ARG)"   )  
								} 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
			}
		}
} 
